name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Call JavaScript function
        run: node your_script.js "YOUR_OPENAI_API_KEY_HERE"

      - name: Use OpenAI API Key
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Using API Key: $OPENAI_API_KEY"
          # Now you can use the API key in your commands
